import { test, before } from "node:test";
import assert from "node:assert/strict";
import supertest from "supertest";
import { createApp } from "../../src/app.js";
import { pool } from "../../src/db/index.js";
import { postAgent } from "../../src/mastra/agents/post-agent.js";

process.env.API_KEY = "integration-test-key";

let app;

before(() => {
  app = createApp();
});

test("GET /posts returns only published posts", async (t) => {
  t.mock.method(pool, "query", async (sql) => {
    assert.match(sql, /WHERE published_at/);
    return { rows: [{ id: "1", titulo: "Post publicado" }] };
  });

  const response = await supertest(app).get("/posts");

  assert.equal(response.status, 200);
  assert.deepEqual(response.body, { data: [{ id: "1", titulo: "Post publicado" }] });
});

test("GET /posts?include=all without an API key is forbidden", async () => {
  const response = await supertest(app).get("/posts?include=all");

  assert.equal(response.status, 403);
});

test("GET /posts?include=all with a valid API key returns every post", async (t) => {
  t.mock.method(pool, "query", async (sql) => {
    assert.doesNotMatch(sql, /WHERE published_at/);
    return { rows: [{ id: "1" }, { id: "2" }] };
  });

  const response = await supertest(app)
    .get("/posts?include=all")
    .set("Authorization", "Bearer integration-test-key");

  assert.equal(response.status, 200);
  assert.equal(response.body.data.length, 2);
});

test("GET /posts returns 500 when the database query fails", async (t) => {
  t.mock.method(pool, "query", async () => {
    throw new Error("db down");
  });

  const response = await supertest(app).get("/posts");

  assert.equal(response.status, 500);
  assert.equal(response.body.message, "Failed to fetch posts");
});

test("GET /posts/:id returns 404 when the post does not exist", async (t) => {
  t.mock.method(pool, "query", async () => ({ rows: [] }));

  const response = await supertest(app).get("/posts/unknown");

  assert.equal(response.status, 404);
});

test("GET /posts/:id returns the post when it exists", async (t) => {
  t.mock.method(pool, "query", async () => ({ rows: [{ id: "1", titulo: "Post" }] }));

  const response = await supertest(app).get("/posts/1");

  assert.equal(response.status, 200);
  assert.deepEqual(response.body.data, { id: "1", titulo: "Post" });
});

test("POST /posts/draft creates a post from the content generated by the agent", async (t) => {
  t.mock.method(postAgent, "generate", async (prompt) => {
    assert.match(prompt, /Ideia de teste/);
    return { object: { titulo: "Gerado", content: "# Conteúdo gerado" } };
  });
  t.mock.method(pool, "query", async (sql, params) => ({
    rows: [{ id: params[0], titulo: params[1], content: params[2] }],
  }));

  const response = await supertest(app).post("/posts/draft").send({ ideia: "Ideia de teste" });

  assert.equal(response.status, 201);
  assert.equal(response.body.post.titulo, "Gerado");
  assert.equal(response.body.post.content, "# Conteúdo gerado");
});

test("POST /posts/draft returns 500 when the agent fails to generate content", async (t) => {
  t.mock.method(postAgent, "generate", async () => {
    throw new Error("agent unavailable");
  });

  const response = await supertest(app).post("/posts/draft").send({ ideia: "Ideia de teste" });

  assert.equal(response.status, 500);
  assert.equal(response.body.message, "Failed to generate post");
});

test("PATCH /posts/:id/approve approves an existing post", async (t) => {
  t.mock.method(pool, "query", async () => ({
    rows: [{ id: "1", approved_at: new Date().toISOString() }],
  }));

  const response = await supertest(app).patch("/posts/1/approve");

  assert.equal(response.status, 200);
  assert.equal(response.body.data.id, "1");
});

test("PATCH /posts/:id/approve returns 404 when the post does not exist", async (t) => {
  t.mock.method(pool, "query", async () => ({ rows: [] }));

  const response = await supertest(app).patch("/posts/unknown/approve");

  assert.equal(response.status, 404);
});

test("DELETE /posts/:id/reject rejects an existing post", async (t) => {
  t.mock.method(pool, "query", async () => ({
    rows: [{ id: "1", rejected_at: new Date().toISOString() }],
  }));

  const response = await supertest(app).delete("/posts/1/reject");

  assert.equal(response.status, 200);
  assert.equal(response.body.data.id, "1");
});

test("DELETE /posts/:id/reject returns 404 when the post does not exist", async (t) => {
  t.mock.method(pool, "query", async () => ({ rows: [] }));

  const response = await supertest(app).delete("/posts/unknown/reject");

  assert.equal(response.status, 404);
});
